### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by vicentematus** [AliasPedroKarim/NetbeansRPC#1]
Is this plugin working still?

**Comment by nostorian** [comment]
the answer is unknown, just try it

**Comment by ghost** [comment]
I have the same question.

**Comment by pedrokarim** [comment]
Sorry for the late reply, this repository is a little bit inactive because the plugin doesn't work anyway, I stopped using netbeans and everyone should stop using netbeans!!! 😁 
I'm going to archive this repository to avoid people falling back on this one as something usable.
